export interface Country {
  name: string;
  capital: string;
  iso: string;
  /** Difficulty level from 1 to 5 for capital (1=easy, 5=hard) */
  capitalLevel: number;
  /** Difficulty level from 1 to 3 for flag (1=easy, 3=hard) */
  flagLevel: number;
}

export const countries: Country[] = [
  {
    name: "France",
    capital: "Paris",
    iso: "fr",
    flagLevel: 1,
    capitalLevel: 1,
  },
  {
    name: "Allemagne",
    capital: "Berlin",
    iso: "de",
    flagLevel: 1,
    capitalLevel: 1,
  },
  { name: "Italie", capital: "Rome", iso: "it", flagLevel: 1, capitalLevel: 1 },
  {
    name: "Espagne",
    capital: "Madrid",
    iso: "es",
    flagLevel: 1,
    capitalLevel: 1,
  },
  {
    name: "Royaume-Uni",
    capital: "Londres",
    iso: "gb",
    flagLevel: 1,
    capitalLevel: 1,
  },
  {
    name: "États-Unis",
    capital: "Washington D.C.",
    iso: "us",
    flagLevel: 1,
    capitalLevel: 2,
  },
  { name: "Japon", capital: "Tokyo", iso: "jp", flagLevel: 1, capitalLevel: 2 },
  { name: "Chine", capital: "Pékin", iso: "cn", flagLevel: 2, capitalLevel: 3 },
  {
    name: "Brésil",
    capital: "Brasília",
    iso: "br",
    flagLevel: 2,
    capitalLevel: 3,
  },
  {
    name: "Canada",
    capital: "Ottawa",
    iso: "ca",
    flagLevel: 1,
    capitalLevel: 4,
  },
  {
    name: "Australie",
    capital: "Canberra",
    iso: "au",
    flagLevel: 2,
    capitalLevel: 4,
  },
  {
    name: "Russie",
    capital: "Moscou",
    iso: "ru",
    flagLevel: 2,
    capitalLevel: 1,
  },
  {
    name: "Mexique",
    capital: "Mexico",
    iso: "mx",
    flagLevel: 2,
    capitalLevel: 2,
  },
  {
    name: "Argentine",
    capital: "Buenos Aires",
    iso: "ar",
    flagLevel: 2,
    capitalLevel: 4,
  },
  {
    name: "Inde",
    capital: "New Delhi",
    iso: "in",
    flagLevel: 2,
    capitalLevel: 5,
  },
  {
    name: "Égypte",
    capital: "Le Caire",
    iso: "eg",
    flagLevel: 3,
    capitalLevel: 3,
  },
  {
    name: "Grèce",
    capital: "Athènes",
    iso: "gr",
    flagLevel: 1,
    capitalLevel: 1,
  },
  {
    name: "Portugal",
    capital: "Lisbonne",
    iso: "pt",
    flagLevel: 1,
    capitalLevel: 1,
  },
  {
    name: "Pays-Bas",
    capital: "Amsterdam",
    iso: "nl",
    flagLevel: 2,
    capitalLevel: 2,
  },
  {
    name: "Suède",
    capital: "Stockholm",
    iso: "se",
    flagLevel: 3,
    capitalLevel: 4,
  },
  {
    name: "Belgique",
    capital: "Bruxelles",
    iso: "be",
    flagLevel: 1,
    capitalLevel: 1,
  },
  {
    name: "Suisse",
    capital: "Berne",
    iso: "ch",
    flagLevel: 1,
    capitalLevel: 4,
  },
  {
    name: "Norvège",
    capital: "Oslo",
    iso: "no",
    flagLevel: 3,
    capitalLevel: 4,
  },
  {
    name: "Danemark",
    capital: "Copenhague",
    iso: "dk",
    flagLevel: 3,
    capitalLevel: 4,
  },
  {
    name: "Finlande",
    capital: "Helsinki",
    iso: "fi",
    flagLevel: 3,
    capitalLevel: 4,
  },
  {
    name: "Autriche",
    capital: "Vienne",
    iso: "at",
    flagLevel: 2,
    capitalLevel: 3,
  },
  {
    name: "Pologne",
    capital: "Varsovie",
    iso: "pl",
    flagLevel: 3,
    capitalLevel: 3,
  },
  {
    name: "Turquie",
    capital: "Ankara",
    iso: "tr",
    flagLevel: 2,
    capitalLevel: 4,
  },
  { name: "Maroc", capital: "Rabat", iso: "ma", flagLevel: 2, capitalLevel: 6 },
  {
    name: "Afrique du Sud",
    capital: "Pretoria",
    iso: "za",
    flagLevel: 2,
    capitalLevel: 5,
  },
  {
    name: "Israël",
    capital: "Jérusalem",
    iso: "il",
    flagLevel: 1,
    capitalLevel: 2,
  },
  {
    name: "Corée du Sud",
    capital: "Séoul",
    iso: "kr",
    flagLevel: 2,
    capitalLevel: 4,
  },
  {
    name: "Indonésie",
    capital: "Jakarta",
    iso: "id",
    flagLevel: 3,
    capitalLevel: 7,
  },
  {
    name: "Arabie Saoudite",
    capital: "Riyad",
    iso: "sa",
    flagLevel: 4,
    capitalLevel: 8,
  },
  {
    name: "Iran",
    capital: "Téhéran",
    iso: "ir",
    flagLevel: 2,
    capitalLevel: 5,
  },
  {
    name: "Hongrie",
    capital: "Budapest",
    iso: "hu",
    flagLevel: 2,
    capitalLevel: 5,
  },
  {
    name: "Thaïlande",
    capital: "Bangkok",
    iso: "th",
    flagLevel: 4,
    capitalLevel: 6,
  },
  {
    name: "Roumanie",
    capital: "Bucarest",
    iso: "ro",
    flagLevel: 3,
    capitalLevel: 5,
  },
  {
    name: "Ukraine",
    capital: "Kyiv",
    iso: "ua",
    flagLevel: 2,
    capitalLevel: 3,
  },
  {
    name: "Nigeria",
    capital: "Abuja",
    iso: "ng",
    flagLevel: 3,
    capitalLevel: 9,
  },
  {
    name: "Colombie",
    capital: "Bogotá",
    iso: "co",
    flagLevel: 3,
    capitalLevel: 6,
  },
  { name: "Pérou", capital: "Lima", iso: "pe", flagLevel: 3, capitalLevel: 6 },
  {
    name: "Chili",
    capital: "Santiago",
    iso: "cl",
    flagLevel: 2,
    capitalLevel: 5,
  },
  {
    name: "Venezuela",
    capital: "Caracas",
    iso: "ve",
    flagLevel: 3,
    capitalLevel: 6,
  },
  {
    name: "Algérie",
    capital: "Alger",
    iso: "dz",
    flagLevel: 2,
    capitalLevel: 1,
  },
  {
    name: "Tunisie",
    capital: "Tunis",
    iso: "tn",
    flagLevel: 2,
    capitalLevel: 1,
  },
  {
    name: "Libye",
    capital: "Tripoli",
    iso: "ly",
    flagLevel: 4,
    capitalLevel: 5,
  },
  {
    name: "Éthiopie",
    capital: "Addis-Abeba",
    iso: "et",
    flagLevel: 4,
    capitalLevel: 7,
  },
  {
    name: "Kenya",
    capital: "Nairobi",
    iso: "ke",
    flagLevel: 4,
    capitalLevel: 7,
  },
  { name: "Ghana", capital: "Accra", iso: "gh", flagLevel: 4, capitalLevel: 8 },
  {
    name: "Pakistan",
    capital: "Islamabad",
    iso: "pk",
    flagLevel: 4,
    capitalLevel: 7,
  },
  {
    name: "Bangladesh",
    capital: "Dacca",
    iso: "bd",
    flagLevel: 5,
    capitalLevel: 8,
  },
  {
    name: "Philippines",
    capital: "Manille",
    iso: "ph",
    flagLevel: 5,
    capitalLevel: 6,
  },
  {
    name: "Vietnam",
    capital: "Hanoï",
    iso: "vn",
    flagLevel: 4,
    capitalLevel: 6,
  },
  {
    name: "Malaisie",
    capital: "Kuala Lumpur",
    iso: "my",
    flagLevel: 5,
    capitalLevel: 7,
  },
  { name: "Irak", capital: "Bagdad", iso: "iq", flagLevel: 3, capitalLevel: 5 },
  { name: "Syrie", capital: "Damas", iso: "sy", flagLevel: 4, capitalLevel: 6 },
  {
    name: "Serbie",
    capital: "Belgrade",
    iso: "rs",
    flagLevel: 2,
    capitalLevel: 3,
  },
  {
    name: "Croatie",
    capital: "Zagreb",
    iso: "hr",
    flagLevel: 2,
    capitalLevel: 4,
  },
  {
    name: "Rép. tchèque",
    capital: "Prague",
    iso: "cz",
    flagLevel: 2,
    capitalLevel: 2,
  },
  {
    name: "Bulgarie",
    capital: "Sofia",
    iso: "bg",
    flagLevel: 3,
    capitalLevel: 5,
  },
  {
    name: "Slovaquie",
    capital: "Bratislava",
    iso: "sk",
    flagLevel: 3,
    capitalLevel: 6,
  },
  {
    name: "Cuba",
    capital: "La Havane",
    iso: "cu",
    flagLevel: 2,
    capitalLevel: 3,
  },
  {
    name: "Émirats arabes unis",
    capital: "Abou Dabi",
    iso: "ae",
    flagLevel: 4,
    capitalLevel: 5,
  },
  {
    name: "Nouvelle-Zélande",
    capital: "Wellington",
    iso: "nz",
    flagLevel: 3,
    capitalLevel: 8,
  },
  {
    name: "Irlande",
    capital: "Dublin",
    iso: "ie",
    flagLevel: 1,
    capitalLevel: 1,
  },
  {
    name: "Corée du Nord",
    capital: "Pyongyang",
    iso: "kp",
    flagLevel: 2,
    capitalLevel: 6,
  },
  {
    name: "Uruguay",
    capital: "Montevideo",
    iso: "uy",
    flagLevel: 2,
    capitalLevel: 3,
  },
  {
    name: "Singapour",
    capital: "Singapour",
    iso: "sg",
    flagLevel: 5,
    capitalLevel: 3,
  },
  {
    name: "Jordanie",
    capital: "Amman",
    iso: "jo",
    flagLevel: 4,
    capitalLevel: 9,
  },
  {
    name: "Liban",
    capital: "Beyrouth",
    iso: "lb",
    flagLevel: 4,
    capitalLevel: 5,
  },
  {
    name: "Ouzbékistan",
    capital: "Tachkent",
    iso: "uz",
    flagLevel: 5,
    capitalLevel: 13,
  },
  {
    name: "Kazakhstan",
    capital: "Astana",
    iso: "kz",
    flagLevel: 5,
    capitalLevel: 8,
  },
  {
    name: "Azerbaïdjan",
    capital: "Bakou",
    iso: "az",
    flagLevel: 5,
    capitalLevel: 7,
  },
  {
    name: "Géorgie",
    capital: "Tbilissi",
    iso: "ge",
    flagLevel: 4,
    capitalLevel: 9,
  },
  {
    name: "Mongolie",
    capital: "Oulan-Bator",
    iso: "mn",
    flagLevel: 5,
    capitalLevel: 9,
  },
  {
    name: "Myanmar",
    capital: "Naypyidaw",
    iso: "mm",
    flagLevel: 5,
    capitalLevel: 15,
  },
  {
    name: "Tanzanie",
    capital: "Dodoma",
    iso: "tz",
    flagLevel: 5,
    capitalLevel: 10,
  },
  {
    name: "Zambie",
    capital: "Lusaka",
    iso: "zm",
    flagLevel: 5,
    capitalLevel: 10,
  },
  {
    name: "Bélarus",
    capital: "Minsk",
    iso: "by",
    flagLevel: 3,
    capitalLevel: 5,
  },
  {
    name: "Slovénie",
    capital: "Ljubljana",
    iso: "si",
    flagLevel: 3,
    capitalLevel: 6,
  },
  {
    name: "Moldavie",
    capital: "Chișinău",
    iso: "md",
    flagLevel: 3,
    capitalLevel: 14,
  },
  {
    name: "Koweït",
    capital: "Koweït City",
    iso: "kw",
    flagLevel: 4,
    capitalLevel: 3,
  },
  {
    name: "Mozambique",
    capital: "Maputo",
    iso: "mz",
    flagLevel: 4,
    capitalLevel: 10,
  },
  {
    name: "Sri Lanka",
    capital: "Sri Jayawardenepura Kotte",
    iso: "lk",
    flagLevel: 4,
    capitalLevel: 9,
  },
  {
    name: "Oman",
    capital: "Mascate",
    iso: "om",
    flagLevel: 4,
    capitalLevel: 8,
  },
  {
    name: "Bhoutan",
    capital: "Thimphou",
    iso: "bt",
    flagLevel: 4,
    capitalLevel: 13,
  },
  {
    name: "Laos",
    capital: "Vientiane",
    iso: "la",
    flagLevel: 5,
    capitalLevel: 12,
  },
  {
    name: "Cambodge",
    capital: "Phnom Penh",
    iso: "kh",
    flagLevel: 4,
    capitalLevel: 12,
  },
  {
    name: "Tadjikistan",
    capital: "Douchanbé",
    iso: "tj",
    flagLevel: 5,
    capitalLevel: 13,
  },
  {
    name: "Turkménistan",
    capital: "Achgabat",
    iso: "tm",
    flagLevel: 4,
    capitalLevel: 12,
  },
  {
    name: "Arménie",
    capital: "Erevan",
    iso: "am",
    flagLevel: 4,
    capitalLevel: 8,
  },
  {
    name: "Afghanistan",
    capital: "Kaboul",
    iso: "af",
    flagLevel: 4,
    capitalLevel: 5,
  },
  {
    name: "Népal",
    capital: "Katmandou",
    iso: "np",
    flagLevel: 3,
    capitalLevel: 8,
  },
  {
    name: "Équateur",
    capital: "Quito",
    iso: "ec",
    flagLevel: 3,
    capitalLevel: 6,
  },
  {
    name: "Bolivie",
    capital: "Sucre",
    iso: "bo",
    flagLevel: 3,
    capitalLevel: 6,
  },
  {
    name: "Paraguay",
    capital: "Asunción",
    iso: "py",
    flagLevel: 3,
    capitalLevel: 7,
  },
  {
    name: "Panama",
    capital: "Panama City",
    iso: "pa",
    flagLevel: 3,
    capitalLevel: 3,
  },
  {
    name: "Costa Rica",
    capital: "San José",
    iso: "cr",
    flagLevel: 3,
    capitalLevel: 6,
  },
  {
    name: "Guatemala",
    capital: "Guatemala City",
    iso: "gt",
    flagLevel: 3,
    capitalLevel: 3,
  },
  {
    name: "Cameroun",
    capital: "Yaoundé",
    iso: "cm",
    flagLevel: 3,
    capitalLevel: 7,
  },
  {
    name: "Côte d'Ivoire",
    capital: "Yamoussoukro",
    iso: "ci",
    flagLevel: 3,
    capitalLevel: 9,
  },
  {
    name: "Sénégal",
    capital: "Dakar",
    iso: "sn",
    flagLevel: 3,
    capitalLevel: 6,
  },
  {
    name: "Angola",
    capital: "Luanda",
    iso: "ao",
    flagLevel: 4,
    capitalLevel: 10,
  },
  {
    name: "Soudan",
    capital: "Khartoum",
    iso: "sd",
    flagLevel: 5,
    capitalLevel: 11,
  },
  {
    name: "Zimbabwe",
    capital: "Harare",
    iso: "zw",
    flagLevel: 4,
    capitalLevel: 13,
  },
  {
    name: "Albanie",
    capital: "Tirana",
    iso: "al",
    flagLevel: 2,
    capitalLevel: 6,
  },
  {
    name: "Macédoine du Nord",
    capital: "Skopje",
    iso: "mk",
    flagLevel: 2,
    capitalLevel: 13,
  },
  {
    name: "Lituanie",
    capital: "Vilnius",
    iso: "lt",
    flagLevel: 3,
    capitalLevel: 5,
  },
  {
    name: "Lettonie",
    capital: "Riga",
    iso: "lv",
    flagLevel: 3,
    capitalLevel: 5,
  },
  {
    name: "Estonie",
    capital: "Tallinn",
    iso: "ee",
    flagLevel: 3,
    capitalLevel: 6,
  },
  { name: "Qatar", capital: "Doha", iso: "qa", flagLevel: 2, capitalLevel: 4 },
  {
    name: "Bahreïn",
    capital: "Manama",
    iso: "bh",
    flagLevel: 3,
    capitalLevel: 9,
  },
  { name: "Yémen", capital: "Sanaa", iso: "ye", flagLevel: 3, capitalLevel: 9 },
  {
    name: "Bosnie-Herzégovine",
    capital: "Sarajevo",
    iso: "ba",
    flagLevel: 3,
    capitalLevel: 5,
  },
  {
    name: "Monténégro",
    capital: "Podgorica",
    iso: "me",
    flagLevel: 4,
    capitalLevel: 13,
  },
  {
    name: "Kosovo",
    capital: "Pristina",
    iso: "xk",
    flagLevel: 4,
    capitalLevel: 11,
  },
  {
    name: "Papouasie-Nlle-Guinée",
    capital: "Port Moresby",
    iso: "pg",
    flagLevel: 5,
    capitalLevel: 12,
  },
  {
    name: "Îles Salomon",
    capital: "Honiara",
    iso: "sb",
    flagLevel: 5,
    capitalLevel: 14,
  },
  {
    name: "Vanuatu",
    capital: "Port-Vila",
    iso: "vu",
    flagLevel: 5,
    capitalLevel: 12,
  },
  { name: "Samoa", capital: "Apia", iso: "ws", flagLevel: 5, capitalLevel: 9 },
  {
    name: "Tonga",
    capital: "Nukuʻalofa",
    iso: "to",
    flagLevel: 5,
    capitalLevel: 15,
  },
  {
    name: "Kiribati",
    capital: "South Tarawa",
    iso: "ki",
    flagLevel: 5,
    capitalLevel: 14,
  },
  {
    name: "Nauru",
    capital: "Yaren",
    iso: "nr",
    flagLevel: 5,
    capitalLevel: 14,
  },
  {
    name: "Tuvalu",
    capital: "Funafuti",
    iso: "tv",
    flagLevel: 5,
    capitalLevel: 15,
  },
  { name: "Fidji", capital: "Suva", iso: "fj", flagLevel: 5, capitalLevel: 10 },
  {
    name: "Timor oriental",
    capital: "Dili",
    iso: "tl",
    flagLevel: 5,
    capitalLevel: 14,
  },
  {
    name: "Brunei",
    capital: "Bandar Seri Begawan",
    iso: "bn",
    flagLevel: 4,
    capitalLevel: 15,
  },
  {
    name: "Maldives",
    capital: "Malé",
    iso: "mv",
    flagLevel: 5,
    capitalLevel: 11,
  },
  {
    name: "Seychelles",
    capital: "Victoria",
    iso: "sc",
    flagLevel: 5,
    capitalLevel: 11,
  },
  {
    name: "Maurice",
    capital: "Port-Louis",
    iso: "mu",
    flagLevel: 5,
    capitalLevel: 8,
  },
  {
    name: "Comores",
    capital: "Moroni",
    iso: "km",
    flagLevel: 5,
    capitalLevel: 11,
  },
  {
    name: "São Tomé-et-Príncipe",
    capital: "São Tomé",
    iso: "st",
    flagLevel: 5,
    capitalLevel: 4,
  },
  {
    name: "Cap-Vert",
    capital: "Praia",
    iso: "cv",
    flagLevel: 5,
    capitalLevel: 9,
  },
  {
    name: "Guinée équatoriale",
    capital: "Malabo",
    iso: "gq",
    flagLevel: 5,
    capitalLevel: 10,
  },
  {
    name: "Rép. dém. du Congo",
    capital: "Kinshasa",
    iso: "cd",
    flagLevel: 5,
    capitalLevel: 7,
  },
  {
    name: "Ouganda",
    capital: "Kampala",
    iso: "ug",
    flagLevel: 4,
    capitalLevel: 11,
  },
  {
    name: "Rwanda",
    capital: "Kigali",
    iso: "rw",
    flagLevel: 5,
    capitalLevel: 13,
  },
  {
    name: "Burundi",
    capital: "Gitega",
    iso: "bi",
    flagLevel: 5,
    capitalLevel: 14,
  },
  {
    name: "Djibouti",
    capital: "Djibouti",
    iso: "dj",
    flagLevel: 5,
    capitalLevel: 3,
  },
  {
    name: "Érythrée",
    capital: "Asmara",
    iso: "er",
    flagLevel: 5,
    capitalLevel: 10,
  },
  {
    name: "Somalie",
    capital: "Mogadiscio",
    iso: "so",
    flagLevel: 5,
    capitalLevel: 8,
  },
  {
    name: "Madagascar",
    capital: "Antananarivo",
    iso: "mg",
    flagLevel: 5,
    capitalLevel: 8,
  },
  {
    name: "Malawi",
    capital: "Lilongwe",
    iso: "mw",
    flagLevel: 5,
    capitalLevel: 15,
  },
  {
    name: "Congo",
    capital: "Brazzaville",
    iso: "cg",
    flagLevel: 5,
    capitalLevel: 7,
  },
  {
    name: "Gabon",
    capital: "Libreville",
    iso: "ga",
    flagLevel: 5,
    capitalLevel: 7,
  },
  {
    name: "Lesotho",
    capital: "Maseru",
    iso: "ls",
    flagLevel: 5,
    capitalLevel: 13,
  },
  {
    name: "Eswatini",
    capital: "Mbabane",
    iso: "sz",
    flagLevel: 5,
    capitalLevel: 13,
  },
  {
    name: "Namibie",
    capital: "Windhoek",
    iso: "na",
    flagLevel: 5,
    capitalLevel: 15,
  },
  {
    name: "Botswana",
    capital: "Gaborone",
    iso: "bw",
    flagLevel: 5,
    capitalLevel: 15,
  },
  { name: "Mali", capital: "Bamako", iso: "ml", flagLevel: 4, capitalLevel: 7 },
  {
    name: "Burkina Faso",
    capital: "Ouagadougou",
    iso: "bf",
    flagLevel: 5,
    capitalLevel: 8,
  },
  {
    name: "Niger",
    capital: "Niamey",
    iso: "ne",
    flagLevel: 5,
    capitalLevel: 9,
  },
  {
    name: "Tchad",
    capital: "N'Djamena",
    iso: "td",
    flagLevel: 5,
    capitalLevel: 8,
  },
  {
    name: "Guinée",
    capital: "Conakry",
    iso: "gn",
    flagLevel: 5,
    capitalLevel: 7,
  },
  {
    name: "Guinée-Bissau",
    capital: "Bissau",
    iso: "gw",
    flagLevel: 5,
    capitalLevel: 4,
  },
  {
    name: "Sierra Leone",
    capital: "Freetown",
    iso: "sl",
    flagLevel: 5,
    capitalLevel: 8,
  },
  {
    name: "Liberia",
    capital: "Monrovia",
    iso: "lr",
    flagLevel: 3,
    capitalLevel: 11,
  },
  { name: "Togo", capital: "Lomé", iso: "tg", flagLevel: 5, capitalLevel: 9 },
  {
    name: "Bénin",
    capital: "Porto-Novo",
    iso: "bj",
    flagLevel: 5,
    capitalLevel: 10,
  },
  {
    name: "Mauritanie",
    capital: "Nouakchott",
    iso: "mr",
    flagLevel: 4,
    capitalLevel: 15,
  },
  {
    name: "Gambie",
    capital: "Banjul",
    iso: "gm",
    flagLevel: 5,
    capitalLevel: 10,
  },
  {
    name: "Centrafrique",
    capital: "Bangui",
    iso: "cf",
    flagLevel: 4,
    capitalLevel: 11,
  },
  {
    name: "Soudan du Sud",
    capital: "Djouba",
    iso: "ss",
    flagLevel: 5,
    capitalLevel: 10,
  },
  {
    name: "Honduras",
    capital: "Tegucigalpa",
    iso: "hn",
    flagLevel: 4,
    capitalLevel: 15,
  },
  {
    name: "Nicaragua",
    capital: "Managua",
    iso: "ni",
    flagLevel: 4,
    capitalLevel: 9,
  },
  {
    name: "El Salvador",
    capital: "San Salvador",
    iso: "sv",
    flagLevel: 4,
    capitalLevel: 4,
  },
  {
    name: "Belize",
    capital: "Belmopan",
    iso: "bz",
    flagLevel: 4,
    capitalLevel: 14,
  },
  {
    name: "Haïti",
    capital: "Port-au-Prince",
    iso: "ht",
    flagLevel: 4,
    capitalLevel: 8,
  },
  {
    name: "Jamaïque",
    capital: "Kingston",
    iso: "jm",
    flagLevel: 2,
    capitalLevel: 7,
  },
  {
    name: "Trinité-et-Tobago",
    capital: "Port of Spain",
    iso: "tt",
    flagLevel: 5,
    capitalLevel: 11,
  },
  {
    name: "Barbade",
    capital: "Bridgetown",
    iso: "bb",
    flagLevel: 4,
    capitalLevel: 11,
  },
  {
    name: "Bahamas",
    capital: "Nassau",
    iso: "bs",
    flagLevel: 5,
    capitalLevel: 8,
  },
  {
    name: "Dominique",
    capital: "Roseau",
    iso: "dm",
    flagLevel: 5,
    capitalLevel: 12,
  },
  {
    name: "Sainte-Lucie",
    capital: "Castries",
    iso: "lc",
    flagLevel: 5,
    capitalLevel: 14,
  },
  {
    name: "Saint-Vincent",
    capital: "Kingstown",
    iso: "vc",
    flagLevel: 5,
    capitalLevel: 12,
  },
  {
    name: "Antigua-et-Barbuda",
    capital: "Saint John's",
    iso: "ag",
    flagLevel: 5,
    capitalLevel: 12,
  },
  {
    name: "Saint-Kitts-et-Nevis",
    capital: "Basseterre",
    iso: "kn",
    flagLevel: 5,
    capitalLevel: 12,
  },
  {
    name: "Grenade",
    capital: "Saint-Georges",
    iso: "gd",
    flagLevel: 5,
    capitalLevel: 12,
  },
  {
    name: "Guyana",
    capital: "Georgetown",
    iso: "gy",
    flagLevel: 5,
    capitalLevel: 9,
  },
  {
    name: "Suriname",
    capital: "Paramaribo",
    iso: "sr",
    flagLevel: 5,
    capitalLevel: 14,
  },
  {
    name: "Islande",
    capital: "Reykjavik",
    iso: "is",
    flagLevel: 3,
    capitalLevel: 5,
  },
  {
    name: "Luxembourg",
    capital: "Luxembourg",
    iso: "lu",
    flagLevel: 3,
    capitalLevel: 1,
  },
  {
    name: "Malte",
    capital: "La Valette",
    iso: "mt",
    flagLevel: 4,
    capitalLevel: 6,
  },
  {
    name: "Chypre",
    capital: "Nicosie",
    iso: "cy",
    flagLevel: 2,
    capitalLevel: 5,
  },
  {
    name: "Andorre",
    capital: "Andorre-la-Vieille",
    iso: "ad",
    flagLevel: 3,
    capitalLevel: 3,
  },
  {
    name: "Monaco",
    capital: "Monaco",
    iso: "mc",
    flagLevel: 3,
    capitalLevel: 1,
  },
  {
    name: "Liechtenstein",
    capital: "Vaduz",
    iso: "li",
    flagLevel: 4,
    capitalLevel: 6,
  },
  {
    name: "Saint-Marin",
    capital: "Saint-Marin",
    iso: "sm",
    flagLevel: 4,
    capitalLevel: 1,
  },
  {
    name: "Vatican",
    capital: "Vatican",
    iso: "va",
    flagLevel: 3,
    capitalLevel: 1,
  },
  {
    name: "Kirghizistan",
    capital: "Bichkek",
    iso: "kg",
    flagLevel: 4,
    capitalLevel: 13,
  },
  {
    name: "Dominicaine (Rép.)",
    capital: "Saint-Domingue",
    iso: "do",
    flagLevel: 5,
    capitalLevel: 9,
  },
  {
    name: "Libération (Palau)",
    capital: "Ngerulmud",
    iso: "pw",
    flagLevel: 5,
    capitalLevel: 15,
  },
  {
    name: "Micronésie",
    capital: "Palikir",
    iso: "fm",
    flagLevel: 4,
    capitalLevel: 15,
  },
  {
    name: "Îles Marshall",
    capital: "Majuro",
    iso: "mh",
    flagLevel: 5,
    capitalLevel: 13,
  },
  {
    name: "Palestine",
    capital: "Ramallah",
    iso: "ps",
    flagLevel: 4,
    capitalLevel: 8,
  },
  {
    name: "Niue",
    capital: "Alofi",
    iso: "nu",
    flagLevel: 5,
    capitalLevel: 14,
  },
];
